### ISSUE TITLE
FGD-211: Set dim-level card bug

### ISSUE THREAD

**Issue by goyaweb** [athombv/com.fibaro#125] opened 2017-03-21 10:13 UTC
When dim level is set the light turns on.
expected behavior: dim level set without light turning on.

**Comment by caseda** [comment] 2017-03-21 10:36
Expected behavior?
Then all other lighting devices have it wrong I guess, including all other zwave devices.

All dimmable devices turn on when setting a dim level, athom even needed to implement an extra option to stop the on command with zwave since it already turns on when setting a dim level.

And is not possible to change this behavior if it is not settable like the dimmer 2 with a build-in parameter

You can work around this with a better logic number slider device.
And use that value tag as a dim level.

**Comment by goyaweb** [comment] 2017-03-21 10:42
I thought the extra option (setondim) was implemented to prevent this behavior, see Emile's remark here:
"As of Homey v1.1.5, for a capability onoff a capability option setOnDim can be set to false to prevent Homey from sending an onoff=true when also setting a dim."
https://github.com/athombv/homey/issues/934#issuecomment-277711659

**Comment by caseda** [comment] 2017-03-21 10:46
The on command made it so the dimmer would fall back into the old value (on command = previous value)
so it would dim to the set level, and then return to the old value thanks to the on command.

**Comment by RobinBol** [comment] 2017-04-24 13:12
Will close this issue as it is not really a bug

**Closed by RobinBol** 2017-04-24 13:12 UTC
