### ISSUE TITLE
Universal Binary Sensor (FGBS-001) Problems on Homey 1.5.8

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.fibaro#212] opened 2018-03-16 18:13 UTC
**Homey:** 1.5.8
**Fibaro:** v1.5.17 - 18.01.18

Since updating Homey to from 1.5.3 to 1.5.8, my universal binary sensor (FGBS-001) just down't work anymore. I mean, come on guys, this is my doorbell button. Now I have no doorbell because of a firmware update.

If I look on Homey at the device and then bush my doorbell button, I no longer see the switch switching (in  other words, that input 1 closes and then opens again), hence the doorbell is never triggered.

I did however see that it sends information as things appear in the log.

Below log is from me pressing the button twice.

```
2018-03-16T18:07:18.046Z | Node[25]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d0202200100
2018-03-16T18:07:18.047Z | Node[25]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[2]},"Properties1":{"Source End Point":2,"Res":false},"Properties2 (Raw)":{"type":"Buffer","data":[2]},"Properties2":{"Destination End Point":2,"Bit address":false},"Command Class (Raw)":{"type":"Buffer","data":[32]},"Command Class":32,"Command (Raw)":{"type":"Buffer","data":[1]},"Command":1,"Parameter":{"type":"Buffer","data":[0]}}
2018-03-16T18:07:18.059Z | Node[25]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_BASIC, data 0x0100
2018-03-16T18:07:19.244Z | Node[25]: Received application command for COMMAND_CLASS_SCENE_ACTIVATION, data: 0x0114ff
2018-03-16T18:07:19.245Z | Node[25]: [COMMAND_CLASS_SCENE_ACTIVATION] {"Scene ID (Raw)":{"type":"Buffer","data":[20]},"Scene ID":20,"Dimming Duration (Raw)":{"type":"Buffer","data":[255]},"Dimming Duration":"configured dimming duration"}
2018-03-16T18:07:20.431Z | Node[25]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d0202200100
2018-03-16T18:07:20.432Z | Node[25]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[2]},"Properties1":{"Source End Point":2,"Res":false},"Properties2 (Raw)":{"type":"Buffer","data":[2]},"Properties2":{"Destination End Point":2,"Bit address":false},"Command Class (Raw)":{"type":"Buffer","data":[32]},"Command Class":32,"Command (Raw)":{"type":"Buffer","data":[1]},"Command":1,"Parameter":{"type":"Buffer","data":[0]}}
2018-03-16T18:07:20.446Z | Node[25]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_BASIC, data 0x0100
2018-03-16T18:07:21.626Z | Node[25]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d02022001ff
2018-03-16T18:07:21.627Z | Node[25]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[2]},"Properties1":{"Source End Point":2,"Res":false},"Properties2 (Raw)":{"type":"Buffer","data":[2]},"Properties2":{"Destination End Point":2,"Bit address":false},"Command Class (Raw)":{"type":"Buffer","data":[32]},"Command Class":32,"Command (Raw)":{"type":"Buffer","data":[1]},"Command":1,"Parameter":{"type":"Buffer","data":[255]}}
2018-03-16T18:07:21.638Z | Node[25]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_BASIC, data 0x01ff
2018-03-16T18:07:22.828Z | Node[25]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d02022001ff
2018-03-16T18:07:22.829Z | Node[25]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[2]},"Properties1":{"Source End Point":2,"Res":false},"Properties2 (Raw)":{"type":"Buffer","data":[2]},"Properties2":{"Destination End Point":2,"Bit address":false},"Command Class (Raw)":{"type":"Buffer","data":[32]},"Command Class":32,"Command (Raw)":{"type":"Buffer","data":[1]},"Command":1,"Parameter":{"type":"Buffer","data":[255]}}
2018-03-16T18:07:22.846Z | Node[25]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_BASIC, data 0x01ff
2018-03-16T18:07:24.057Z | Node[25]: Received application command for COMMAND_CLASS_SCENE_ACTIVATION, data: 0x0114ff
2018-03-16T18:07:24.058Z | Node[25]: [COMMAND_CLASS_SCENE_ACTIVATION] {"Scene ID (Raw)":{"type":"Buffer","data":[20]},"Scene ID":20,"Dimming Duration (Raw)":{"type":"Buffer","data":[255]},"Dimming Duration":"configured dimming duration"}
2018-03-16T18:07:25.264Z | Node[25]: Received application command for COMMAND_CLASS_SCENE_ACTIVATION, data: 0x0114ff
2018-03-16T18:07:25.267Z | Node[25]: [COMMAND_CLASS_SCENE_ACTIVATION] {"Scene ID (Raw)":{"type":"Buffer","data":[20]},"Scene ID":20,"Dimming Duration (Raw)":{"type":"Buffer","data":[255]},"Dimming Duration":"configured dimming duration"}


```

**Comment by Veldkornet** [comment] 2018-03-16 18:23
I decided to try out the "heal" action. Afterwards, pushing the doorbell button worked. Below the log from a "working"scenario. It only stays working for a short time though. Then it's broken again.
My ZWave network is a complete F*** up after the update, all of the devices are either slow or just don't work.

```
2018-03-16T18:19:39.627Z | Node[25]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d0202200100
2018-03-16T18:19:39.628Z | Node[25]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[2]},"Properties1":{"Source End Point":2,"Res":false},"Properties2 (Raw)":{"type":"Buffer","data":[2]},"Properties2":{"Destination End Point":2,"Bit address":false},"Command Class (Raw)":{"type":"Buffer","data":[32]},"Command Class":32,"Command (Raw)":{"type":"Buffer","data":[1]},"Command":1,"Parameter":{"type":"Buffer","data":[0]}}
2018-03-16T18:19:39.639Z | Node[25]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_BASIC, data 0x0100
2018-03-16T18:19:40.812Z | Node[25]: Received application command for COMMAND_CLASS_SCENE_ACTIVATION, data: 0x0115ff
2018-03-16T18:19:40.812Z | Node[25]: [COMMAND_CLASS_SCENE_ACTIVATION] {"Scene ID (Raw)":{"type":"Buffer","data":[21]},"Scene ID":21,"Dimming Duration (Raw)":{"type":"Buffer","data":[255]},"Dimming Duration":"configured dimming duration"}
2018-03-16T18:19:42.059Z | Node[25]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d02022001ff
2018-03-16T18:19:42.061Z | Node[25]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[2]},"Properties1":{"Source End Point":2,"Res":false},"Properties2 (Raw)":{"type":"Buffer","data":[2]},"Properties2":{"Destination End Point":2,"Bit address":false},"Command Class (Raw)":{"type":"Buffer","data":[32]},"Command Class":32,"Command (Raw)":{"type":"Buffer","data":[1]},"Command":1,"Parameter":{"type":"Buffer","data":[255]}}
2018-03-16T18:19:42.075Z | Node[25]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_BASIC, data 0x01ff
2018-03-16T18:19:43.555Z | Node[25]: Received application command for COMMAND_CLASS_MULTI_CHANNEL, data: 0x0d02022001ff
2018-03-16T18:19:43.561Z | Node[25]: [COMMAND_CLASS_MULTI_CHANNEL] {"Properties1 (Raw)":{"type":"Buffer","data":[2]},"Properties1":{"Source End Point":2,"Res":false},"Properties2 (Raw)":{"type":"Buffer","data":[2]},"Properties2":{"Destination End Point":2,"Bit address":false},"Command Class (Raw)":{"type":"Buffer","data":[32]},"Command Class":32,"Command (Raw)":{"type":"Buffer","data":[1]},"Command":1,"Parameter":{"type":"Buffer","data":[255]}}
2018-03-16T18:19:43.620Z | Node[25]: Decapsulated frame from COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_BASIC, data 0x01ff
2018-03-16T18:19:44.372Z | Node[25]: Received application command for COMMAND_CLASS_SCENE_ACTIVATION, data: 0x0114ff
2018-03-16T18:19:44.373Z | Node[25]: [COMMAND_CLASS_SCENE_ACTIVATION] {"Scene ID (Raw)":{"type":"Buffer","data":[20]},"Scene ID":20,"Dimming Duration (Raw)":{"type":"Buffer","data":[255]},"Dimming Duration":"configured dimming duration"}


```

**Comment by Arjanvde** [comment] 2018-03-18 20:02
sames as https://github.com/athombv/com.fibaro/issues/198

**Comment by jeroenvollenbrock** [comment] 2018-03-19 10:54
Closing as duplicate of #198

**Closed by jeroenvollenbrock** 2018-03-19 10:54 UTC
