### ISSUE TITLE
Motion sensor does not cancel motion/tamper alarms

### ISSUE THREAD

**Issue by fredrikj83** [athombv/com.fibaro#189] opened 2017-12-01 06:58 UTC
I have two Fibaro motion sensors (z-wave plus). Last night I noticed that the motion alarm from one of them is not being cancelled after the (default) cancellation time has passed. 

I then triggered the tamper alarm by moving the sensor, and I could see that the tamper alarm was triggered but now that too isn't being cancelled. The temp and light values seem to update in Homey so I'm pretty sure it's not a coverage issue (the sensor is only about 3 meters from the Homey).

Not sure how to debug this. Has this issue been reported before or seen by others?

**Comment by caseda** [comment] 2017-12-01 07:12
Issue has been there for a while now, and is not app related.

Homey fw v1.5.6 will most likely fix this issue.

**Comment by fredrikj83** [comment] 2017-12-01 07:18
@caseda OK, thanks. I will await 1.5.6 then to see if it is resolved.

**Comment by JesperJanssen** [comment] 2017-12-29 07:36
I'm on Homey Firmware Version: 1.5.6-rc.7 and I still have this problem. Do more people still have this problem.

I think we need to re-open this issue

**Comment by cbho** [comment] 2017-12-29 08:49
Same problem here (FW 1.5.6-rc.7):
Tamper alarm continously on, motion alarm turns off more reliably than before update to rc.7, though.

**Comment by fredrikj83** [comment] 2018-03-20 19:43
Still having issues in 1.5.8. Deleted device and re-added but with no luck. After first having trouble adding the device at all, I finally succeeded. Now the motion sensor alarm does not seem to be cancelled in Homey.

Here's an excerpt from a mail sent to Athom support (@Moszkowizz) - not a full log, but let me know what you need and I'll make sure to get whatever I can.

Looking at the device, I see that the Motion Alarm keeps flashing as if it's never reset. If I check the log while moving in front of the sensor, I do see traffic between Homey and the motion sensor node. Also, 30 seconds later I see traffic again. This makes me think that the cancellation of the motion alarm is indeed sent by the sensor (but looking at the log I can't really understand what it means). If I look at the "Illumination report" traffic, I get more human readable data like this:

`Node[34]: [COMMAND_CLASS_SENSOR_MULTILEVEL] {"Sensor Type (Raw)":{"type":"Buffer","data":[3]},"Sensor Type":"Luminance (version 1)","Level (Raw)":{"type":"Buffer","data":[10]},"Level":{"Size":2,"Scale":1,"Precision":0},"Sensor Value":{"type":"Buffer","data":[0,3]},"Sensor Value (Parsed)":3} 
`
From that I can easily read that it's an illumination report and the parsed value is 3 (corresponds to what I see when looking at the device - 3 lx). But the data for motion alarm contains a lot more data and isn't logged in a readable way (at least from my point of view). It looks something like this:

```
Node[21]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
2018-03-20T19:19:36.590Z
Node[21]: [COMMAND_CLASS_SECURITY] {}
2018-03-20T19:19:36.590Z
Node[21]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_REPORT] {"type":"Buffer","data":[140,254,150,17,10,105,50,84]}
2018-03-20T19:19:36.591Z
Node[21]: sendData to COMMAND_CLASS_SECURITY, params 0x808cfe96110a693254
2018-03-20T19:19:36.594Z
Command[2041] start: sendData
2018-03-20T19:19:36.594Z
ProcessSendData[2032]: To node: 21 with data: 0x98808cfe96110a693254 and txOptions: AUTO_ROUTE,EXPLORE
2018-03-20T19:19:36.616Z
Node[21]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
```

And since the motion alarm isn't cancelled in Homey, I guess that's why it doesn't trigger when new motion is detected.

**Comment by jeroenvollenbrock** [comment] 2018-03-27 09:15
Closing as duplicate of athombv/homey#2267

**Closed by jeroenvollenbrock** 2018-03-27 09:15 UTC
