### ISSUE TITLE
Fibaro NEW FGSD-002 Smoke Sensor not reconized on Homey

### ISSUE THREAD

**Issue by Handyman4u** [athombv/com.fibaro#230] opened 2018-05-18 10:07 UTC
Metadata
•Homey Version: Homey Firmware Versie: 1.5.11
•Homey Log Code:
•Smartphone Platform:
•Smartphone App Version:

If related to a Homey App:
•Homey App Version:v1.5.17
•Homey App Log Code: cfbb71e3-324b-47b0-be7b-4dfa9b69a00e
•Affected Devices (preferably product codes): FGSD-002 ZW5 v3.3

What did you try to achieve?
 trying to add an new Fibaro Smoke sensor FGSD-002 ZW5 v3.3 Build April 2018

What did you expect as result?
 reconizion of an Fibaro Smoke detector on the Homey

What was the result?
 New Fibaro Smoke sensor is not reconized on the homey and will result in an Unknown Z-wave device

Any other remarks

tryed 2 new Fibaro Smoke detectors (April 2018) on 2 diffrent Homey's with same results.

ATHOMBV Issue: #2477 on Gtihub redirected to Fibaro

**Comment by jeroenvollenbrock** [comment] 2018-05-31 18:03
Closing as duplicate of https://github.com/athombv/homey/issues/2477

**Closed by jeroenvollenbrock** 2018-05-31 18:03 UTC
