### ISSUE TITLE
Fibaro door/window sensor 2 -> stays on "Sabotage Alarm Triggered"

### ISSUE THREAD

**Issue by vk900** [athombv/com.fibaro#176] opened 2017-10-10 08:17 UTC
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

Trying to get the Sabotage alarm to be triggered when applicable on a Fibaro Door/window Sensor 2

*Please include detailed steps how we can reproduce the issue*

Basically this issue is created following up: https://forum.athom.com/discussion/3444/fibaro-door-window-sensor-sabotage-triggered (which incorrectly has been marked as "solved")

In short:
- when I add the Door/Windows Sensor 2,  it will be added with the sabotage alarm on, all the time. (doesn't go off when all switches that should trigger sabotage are pressed)
- when I add the Door/Windows Sensor 2 while keeping the button pressed _(clicking it 4 times effectively as you need to keep it pressed at the end)_ during the adding device cycle I don't get the sabotage alarm and it stays on "No" for ever, even when the the cover is opened up.

**What was the result?**

See details above

**What did you expect as result?**

Sabotage Alarm should be off when all switches are pressed and on whenever 1 is unpressed.

**Any other remarks**

Reading through the forum a lot of people have these same issues.

**Please attach a Homey System log (Settings -> System -> Send Log)**

93BE0709FD

**Comment by RobinBol** [comment] 2017-10-10 13:07
Hi! Thanks for your elaborate issue, I have just released an update of the Fibaro app (1.5.10), which is likely to fix your issue. You do need to trigger the tamper alarm once for it to update the state correctly. Please let me know if this fixes your issue!

**Comment by Veldkornet** [comment] 2017-10-10 14:01
I also have this problem!

My app just updated to 1.5.10, but now all of my door/window sensor 2's give an error. I removed and re-added the device to Homey, but it gives the same problem. Log: F76193C4C1

**Comment by RobinBol** [comment] 2017-10-10 14:13
Hm, @Veldkornet that should be solved in 1.5.11 (just released). What are the exact device types you are using?

**Comment by vk900** [comment] 2017-10-10 14:15
So, the tampering alarm is all good now over here (needed to re-add the device though).
Next problem: when I reboot the Homey while the Door/window Sensor 2 is on my desk and the magnet is next to it it boots up triggering the sabotage alarm (which is valid as the switch isn't pushed) but it also start with the contact alarm triggerd. This is invalid.

When I pull the magnet and put it back it clears..

(also my battery monitor doesn't display the status anymore)

**Comment by Veldkornet** [comment] 2017-10-10 14:18
I have the FGDW-002 (1) ZW5 v3.2, is that what you wanted?

I’ll check now in the 1.5.11

FYI, my battery status for most of my Fibaro devices haven’t shown in a while.

**Comment by vk900** [comment] 2017-10-10 14:31
Ive got the v3.2 as well. I removed the device, rebooted Homey, added device again: sensor now shows battery and after a while the correct status on both contact alarm and tampering alarm.

while keeping the sensor without both alarms: "no" i've rebooted Homey to see in what status they boot.
Conclusion: both are good

BUT: when I triggered tampering alarm it goes to "Yes" (valid) and when I triggerd the contact Alarm is goes to "Yes" as well (also valid.) But when I now put back the magnet my Contact Alarm stays in "Yes".....
uurrgghhh... when I move magnet again back and forth it does go well.... i'm now checking if i can reproduce this scenario

**Comment by RobinBol** [comment] 2017-10-10 14:34
That is strange, if you can reproduce, please let me know!

**Comment by vk900** [comment] 2017-10-10 14:36
I can't really... when I tried to reproduce I got it the other way around this time: instead of the contact alarm not going off it was the tampering alarm that didnt go off this time...  

To me this looks like sort of a timing issue between both alarms and the fact that they get cleared in a second or so

**Comment by vk900** [comment] 2017-10-10 14:40
@RobinBol anyway, thanks for your help on this one Robin

**Comment by Veldkornet** [comment] 2017-10-10 14:43
Mine was a little slow to pick up the sabotage changes the first time to update the state correctly, but it seems to be working as expected now. I've tested it a few times.

Thank goodness, I thought it was hardware related :)

HOWEVER, my version 1 devices (FGK-10x) are now a bit wonky. First, the devices weren't working at all. I needed to pull the battery and put it back for it to work. Now, once the sabotage alarm is triggered, it stays triggered, similar to what was happening with the v2 devices before the update.

**Comment by RobinBol** [comment] 2017-10-10 14:44
No problem. I will close this issue, since the problem in the opening post seems to be resolved. However, if you run into new problems please open a new issue!

@Veldkornet Good to hear, regarding the FGK-10x I'd recommend to re-pair once to see if that resolves your issue.

**Closed by RobinBol** 2017-10-10 14:44 UTC
Labels: bug

**Comment by Veldkornet** [comment] 2017-10-10 14:45
I was a bit quick to comment, looks like the devices just aren't making good contact and I just never noticed it before :) So all is good!

**Comment by wencew** [comment] 2018-03-05 20:22
Hi, just installed 3 Fibaro Door Window Sensor 2 and the sabotage alarm stays triggered for all three and performed already many Homey reboots. 
Homey Firmware Versie: 1.5.6
Fibaro App Version: v1.5.17

Any idea when this will be resolved? Let me know if you need additional details.

**Comment by menjuice** [comment] 2018-06-01 20:46
Same here. And it drains the battery. Still with the update and resetting and all.

**Comment by mackann87** [comment] 2018-06-02 12:58
I bought a homey and fibaro door sensor 2, and I can't get it to work correctly se here: https://ufile.io/8exm0 it shows tamper alert all time and contact alarm don't update?

**Comment by JuergenMK** [comment] 2018-11-11 14:56
Same here. More than the half of the "fibaro door/window sensors 2" shows tamper alert directly after inclusion. No change after exclusion and inclusion. Once they are on tamper alert, they stay...
What can be done to alert the sabotage correct?

**Comment by JuergenMK** [comment] 2018-11-25 09:52
I was able to solve the issue and want to share my experience.
The problem was not located on the Homey or on a technical perspective. So, to make it short: it was my mistake and the sabotage feature recognized it well :-)

It was a physical issue with the fibaro door/window sensor ;-) I had to place the sensor differently and used a new M3 tape. I missed to cut out the part for the tamper and verify that the tamper is pressed when sticked to the window (had to play a bit with the tamper and glue a small part on it to get the "pressed" attention).

**Comment by Veldkornet** [comment] 2018-11-25 10:19
No, that’s not the same issue. All of my sensors are making contact correctly. 

I’d be surprised if everyone in this issue and all linked issues just didn’t know how to install a sensor.

**Comment by JuergenMK** [comment] 2018-11-25 10:32
I am not talking about everybody... it's a short wrap-up of my experience and my comment 2 weeks ago...

**Comment by YDind** [comment] 2018-11-25 10:45
Hi all

As I posted on another thread few days ago, I finally discovered that I had
the same problem.

Initially the issue was coming from Homey z-wave range, who made the tamper
cancellation signal not to be received. I sorted it out by adding a wall
switch 1 meter from Homey and it fixed the problem for all my devices
excepted for the Fibaro door sensors.

After having dig a bit more, I also found these sensors have a weak tamper
system, which is very easily damaged / deformed if the sensor is opened /
removed more than once (which of course I did several times due to the
signal range issue).

After having customized the sensors with some tape to make the tamper
mechanism thicker, they work well.

**Comment by JuergenMK** [comment] 2018-11-25 10:51
+1 
I came from FibaroHC2 and Domoticz and there was a feature "network wide inclusion". It seems there is no equal feature available in Homey (or I missed something) and the sensor must be included near the base station. That's one of the reasons why I had to remove a few sensors as well..
