### ISSUE TITLE
FIBARO RGBW does not change the dimming state at power-on

### ISSUE THREAD

**Issue by Korenets** [athombv/com.fibaro#171] opened 2017-09-25 16:20 UTC
FIBARO RGBW Controller FGRGBWM-441 

If the RGBW is turned on, the dimming scale does not automatically change its state

**Comment by RobinBol** [comment] 2017-09-25 16:53
@caseda something you want to take a look at?

**Comment by caseda** [comment] 2017-09-26 13:17
I'll look into it, probably already know what's up, and how to fix it

**Comment by RobinBol** [comment] 2017-10-16 15:09
@caseda do you perhaps have an update? Or is it something I have to look into? Thanks!

**Comment by caseda** [comment] 2017-10-16 15:59
will send in the fix this evening

**Comment by caseda** [comment] 2017-10-17 06:17
Hmm, seems the issue is a bit more weird/stubborn (but then again debugging with 5 modules sending debug info doesn't make it really easy), so will continue fixing this evening.

**Comment by RobinBol** [comment] 2017-12-11 18:36
@Korenets this issue should be solved by now (via caseda's PR), so I'll close this issue for now. If it was not solved please let us know!

**Closed by RobinBol** 2017-12-11 18:36 UTC
Labels: bug
