### ISSUE TITLE
Motion Sensor zwave and zwave +: Closing learning mode

### ISSUE THREAD

**Issue by 2benl** [athombv/com.fibaro#9] opened 2016-07-30 07:20 UTC
After including my FGMS-001-ZW5 Fibaro Motion sensor Z-wave plus my sensor will stay in learning mode till it times out. Inclusion in Homey seems to go ok, but I tought that in previous firmwares the motion sensor noticed it was included and stopt they inclusion mode after connecting with Homey.

I'm not 100% sure this was the case, buth it might be worth looking in to it.

**Comment by caseda** [comment] 2016-07-30 07:38
@2benl 
This is not just for the Z-Wave+ version, the normal version has this as well. (as written in the [Forum post](https://forum.athom.com/discussion/comment/27817/#Comment_27817))

**Comment by RobinBol** [comment] 2016-09-14 14:50
@2benl @caseda Just trying to reproduce the issue, but either I don't understand it correctly, or it seems to be fixed.

So, if I pair a z-wave device it will remain in inclusion mode after it has been paired with Homey? I tried this by pairing the device, and immediately after pairing opening the pairing wizard again (which then should recognize the device still being in inclusion mode). But the inclusion did not restart.

Is there some other way to determine if the node is still in inclusion mode after pairing?

BTW: I don't see this being a real problem, or do you have run into problems concerning this issue?

**Comment by 2benl** [comment] 2016-09-14 14:54
I did try this a few other times because the sensor stopped logging data. Result is always the same. It is not a big issue, but it looks strange. Homey says paring complete while the sensor stays in pairing mode till the timeout.

**Comment by RobinBol** [comment] 2016-09-14 14:55
How do you know the node is still in pairing mode?

**Comment by 2benl** [comment] 2016-09-14 14:55
With the Fibaro motion sensor you can see that the blue light is still on.

**Comment by RobinBol** [comment] 2016-09-14 15:06
I think that just indicates that the node has been woken up, not sure. How long does the ligt remain blue? Here it remains blue for about 30-40 seconds after pairing.

**Comment by 2benl** [comment] 2016-09-14 15:23
Now about the same time you estimate. Before I tought it turned off after it was paired.

**Comment by RobinBol** [comment] 2016-09-14 15:30
Okay, I'll be closing the issue for now (as there does not seem to be a real problem), if you encounter problems with it, please let us know!

**Closed by RobinBol** 2016-09-14 15:30 UTC
