### ISSUE TITLE
Associating dimmer 1 with dimmer 2 and vice versa 

### ISSUE THREAD

**Issue by lvanderree** [athombv/com.fibaro#61] opened 2016-10-21 08:45 UTC
The defined association between a Fibaro Dimmer 1 and Fibaro Dimmer 2 module and the other way arround doesn't seem to work.
Associations among Dimmer 2 modules are working

This has worked when I was using Domoticz with an Aeon Labs USB stick.

I have already removed a Dimmer 1 and Dimmer 2 module from my Homey zwave network, and re-added them with the 0.10.5  firmware and Fibaro app v1.0.16 and set the association again, but that didn't help.

see https://forum.athom.com/discussion/comment/34813/#Comment_34813 as well

**Comment by roelfsre** [comment] 2016-10-30 18:54
Looks like I have the same issue.
 I have a TKB double paddle dimmer (TKB_TZ65D). When I associate a Fibaro single switch v2 to group 2 (for the second padle), it will not respond. Nothing happens. But when I associate a Fibaro wall plug to group 2, I can switch it off and on. Is the TKB home switch not talking Fibaro single switch v2 language or does the Fibaro single switch not understanding the language of the TKB Home switch ?

**Comment by RobinBol** [comment] 2016-11-28 15:34
We might have fixed this issue in homey v1.0.2: `Fixed a bug where Z-Wave reports from Controlled command classes would not get through when sent secure`.

Could you retry? (So re-pair the devices and re-set the association groups) And please let me know if it still doesn't work by then.

**Comment by roelfsre** [comment] 2016-11-28 19:50
Hello Robin Bolscher,


Thank you for your reply, but unfortunately it is still not working. Here is what I did.

I removed the Fibaro Switch from Homey and re-added it again. I added the Node ID to associate it to group 2 of my TKBHome switch. It did not work.

I removed the Fibaro switch again AND I removed the TKBHome switch too. Added them both again and did the association again. Still did not work.

If I associate an Fibaro "tussenstekker", than it is working. I can turn on and off the device with the second paddle on the TKBHome switch. Only the Fibaro 2 single switch is not working.

Strange thing is that I need to fysically connect a switch to S1 and L1 to get the fibaro switch into Homey. I can't just use the small tiny buton on the fibaro switch to do this. After it is added to homey, I can remove the fysical switch and use the Homey app to turn it off and on. (but still not with the second peddle on the TKBHome swith).

Hope this information helps you to find the issue. If I can do anything more to help, or if you need more information, just let me know.


Regards/Groeten,


René

________________________________

**Comment by lvanderree** [comment] 2016-11-28 21:01
For me the same thing. 

I removed the dimmer 1 and readded it, setup the association by adding the node of a dimmer 2 to group 2, but without succes. 
Then removed dimmer 2,and readded it, looked up its ID and set this in group 2 of dimmer 1,but still button 2 did not trigger dimmer 2.

**Comment by RobinBol** [comment] 2016-12-07 11:54
@WeeJeWel seems some (secure?) commands are not passed through.

**Comment by RobinBol** [comment] 2016-12-07 17:13
So I figured out that Homey only sets the correct association group numbers, the rest of the communication (between Dimmer 1 and 2 for example) is not routed through Homey and is directly send from Dimmer 2 to Dimmer 1 for example.

This is therefore not a Homey issue, but probably related to the devices itself and their settings.

**Comment by lvanderree** [comment] 2016-12-07 17:19
I know that it is suppose to be working like that, but what I don't understand is that it did work before, in my domoticz network with an Aeon Labs USB-stick as a controller. So I know the devices are capable of working as described, and my guess is something is different in the Homey network.

If someone can tell me how I can debug this myself I have no problem trying to figure it out.

**Comment by RobinBol** [comment] 2016-12-08 14:07
I am not sure how to debug it. However, you could dig into your devices' settings to see where the difference lies. That is my guess, that devices on Aeon Labs USB/domoticz get different (default) configuration which causes them to forward their commands on specific association groups.

**Comment by lvanderree** [comment] 2017-01-23 10:36
I had some time to retry setting up the association between a Fibaro Dimmer 1 and Fibaro Dimmer 2, and I don't know wat is changed, but this time I'm half way there!

I am running Homey version 1.1.2, with Fibaro app 1.1.9

A Fibaro Dimmer 1 has Node ID 30 and is (of course) NOT securely connected to Homey
A Fibaro Dimmer 2 has Node ID 31 and IS securely connected to Homey

In Dimmer 1 with ID 30 I setup the following association:
group 1: 1
group 2: 1,31
group 3: 1

* I can't figure out if adding ID 1 to group 1 and group 2 is making any difference, but I do this since the documentation says: "The first field in each group is reserved for the network controller." Although I don't know if that means that I should provide it, or that is is hardcoded.  

And in Dimmer 2 with ID 31 I setup the following association:
group 1: 1
group 2: 1
group 3: 1
group 4: 1,30
group 5: 1,30

* again I don't know if adding ID 1 to group 2,3,4 and 5 makes any difference, but the documentation now says: "1 field is reserved for the Z-Wave network main controller".

I also again have added parameter "27,1,0" to Dimmer 2, to let it send non secure commands.

This way I am able to control dimmer 1 (enable/disable and dim its light) by button 2 on dimmer 2.
However I still cannot control dimmer 2 by pressing button 2 on dimmer 1.

Maybe dimmer 1 sends the wrong command class? Or maybe dimmer 2 doesn't accept non secure commands? Or what else can go wrong?

Maybe it is an option to automatically set parameter 27, when an association is made between a secure fibaro dimmer 2 and a non secure device.

**Comment by TedTolboom** [comment] 2017-01-23 11:58
@lvanderree I have a similar experience with the Dimmer-2 (secure) not accepting switch ON or OFF commands from a Fibaro motion sensor (non-plus) that is connected non-secure.

If I use a similar setup with a non-secure devices, they all respond to motion detection (ON and OFF), but if I link it to the dimmer-2 there is no response. 

Although the manual is not explicit about it, the conclusion I drew is that the dimmer-2, if added in secure mode, only accepts commands from secure devices. 
Which does sound logical, why would you implement encryption anyway? Searching the internet, you find multiple similar observations. But Fibaro should be explicit about if in their manual / FAQ.

By modifying parameter 27 (Associations in Z-Wave network security mode), you are able to control a non-secure device (like the dimmer-1) from the dimmer-2, as you demonstrate.

Alternatives to still be able to control the dimmer-2 is either via Homey, or to include the dimmer-2 in non-secure mode. 
For the latter, the dimmer-2 depends on the controller to 'force' non-secure inclusion. It does not have a parameter to force non-secure inclusion it from device side.

**Comment by lvanderree** [comment] 2017-01-23 12:10
@TedTolboom Thanks for your insights, 

your info explains it all indeed.
I once had the setup with the Dimmers 1 and Dimmers 2 working, with Domoticz as a controller, using a Aeon Labs Zwave stick which wasn't plus/secure.

So providing an option to pair in a non-secure way (which is strange, but as can be seen, can be desired) might be the solution.

**Comment by lvanderree** [comment] 2017-01-23 12:13
As an alternative: Is there a way that Homey acts on pressing the 2nd button of a device (I then of course add ID 1 to group 2 of dimmer 1 but can Homey then act on this signal). So I can setup a flow to let Homey control the light by pressing the 2nd button?

**Comment by TedTolboom** [comment] 2017-01-23 12:22
Yes, this is possible. I have a similar flow to trigger based on triple press:
![image](https://cloud.githubusercontent.com/assets/17163431/22203572/0db96640-e16e-11e6-8f5b-d8b4b11cfe61.png)

Different options of the dimmer-2 trigger card:
![image](https://cloud.githubusercontent.com/assets/17163431/22203708/9bbdc1ca-e16e-11e6-9a1f-77890edd960c.png)

**Comment by lvanderree** [comment] 2017-01-23 12:33
Thanks, I was already trying and found out Athom had added these triggers, very nice!

However, they were not working, until I added hiddend parameter "41,1,1" to the Dimmer 1.

This is a nice workarround (since it requires Homey, and more importantly, doesn't allow for dimming by holding the button), until the association works by a non-secure paring option.

**Comment by RobinBol** [comment] 2017-01-23 12:49
@lvanderree 41,1,1 will be set upon pairing (at least if you pair with a recent version of the Fibaro app).

**Comment by caseda** [comment] 2017-01-23 13:10
Was just thinking that it might got to do with this issue: https://github.com/athombv/homey/issues/1285
Since the dimmer 2 uses multichannel for its S1 and S2 inputs

**Comment by TedTolboom** [comment] 2017-02-16 22:18
Just confirmed with a Fibaro Motion Sensor (Z-wave Plus) in combination with a Dimmer-2; in this combination, the sensor is able to switch on the dimmer-2 directly (via association group 2 on the sensor, basic command class). 

So it looks like the dimmer-2 does only accept commands from secure devices.

**Comment by RobinBol** [comment] 2017-02-22 12:59
Thanks @TedTolboom for the confirmation; it seems that this issue is not Homey related, but caused by the way z-wave itself works. Therefore I'll close this issue.

**Closed by RobinBol** 2017-02-22 12:59 UTC
