### ISSUE TITLE
FGMS-001 ZW5 Motion (multi) sensor does not report battery level

### ISSUE THREAD

**Issue by Corvo** [athombv/com.fibaro#40] opened 2016-08-17 06:55 UTC
After starting up Homey (refer to https://github.com/athombv/homey/issues/789 for more info), the Z-Wave network is properly working again except the Motion Sensor.

The Motion sensor is _no longer reporting the battery level_ (motion, tamper, temp and lux are working fine).

_Running Homey v0.9.2, Fiabro App version v1.0.7 in combination with a FGMS-001 ZW5 Motion (multi) sensor (and 5 Fibaro Wall Plugs)._

![homey zones devices](https://cloud.githubusercontent.com/assets/1075840/17727242/4954186e-6458-11e6-818d-4c50abc94b7a.png)

**Comment by Inversion-NL** [comment] 2016-08-17 07:10
Did you at least waited for 24 hours?
My Smoke sensors only report once ever 24 hour, even though their set to report the temperature every hour.

**Comment by Corvo** [comment] 2016-08-17 07:15
I was going through the parameters and hoping to find a report interval... (but didn't find any).
Except the 7200 seconds wake-up, which I assumed would perhaps be the report interval.

Hopefully you're right, I guess we'll find out somewhere at the end of the day.
As soon as the battery report comes in, I'll update & close the issue.

**Comment by Inversion-NL** [comment] 2016-08-17 07:24
I'm want implying you have the same issue but I guess we should at least test it

**Comment by Corvo** [comment] 2016-08-18 05:42
24 hours have passed, and the battery level isn't reported. So for now, I'm guessing it is a bug of some sort.

**Comment by Inversion-NL** [comment] 2016-08-18 06:17
Remove and re-adding it might help?

**Comment by Corvo** [comment] 2016-08-18 06:27
If possible I'd like to avoid that... simply because I don't want to fix/check all flows. :sweat_smile: 
And for now, the battery level isn't that crucial (yet).

**Comment by Corvo** [comment] 2016-08-30 05:41
Just an update about the current status:

The battery level still isn't reported. Using sensor's wake-up function (pressing the control button 3 times) yields no results, though all other values were updated. Rebooting Homey hasn't remedied the problem and the newer (v0.9.3) update hasn't either.

**Comment by ThaYoung1** [comment] 2016-09-03 05:35
I'm experiencing the same issue here

**Comment by RobinBol** [comment] 2016-09-14 15:58
The only reason I can think of is that you paired with an older version of the app or Homey firmware, which could cause this issue. Tested with the same device and app version 1.0.10 and never was able to reproduce the issue, it might take a while before the values come in though.

I'd recommend to re-pair the device with the latest version of the app, and then report if the problem still exists.

**Comment by jghaanstra** [comment] 2016-11-26 18:42
I have re-paired the Fibaro FGMS-001 ZW5 Motion sensor on Homey firmware 1.0.2 and Fibaro app version 1.1.0 and this issue is still present. I have only once seen a battery status report, that was when I initially paired the sensor somewhere on firmware version 0.8.x.

Since then no more reports of the battery status, not even after repairing.

**Comment by WeeJeWel** [comment] 2016-11-29 15:13
I have debugged this issue by looking at the Z-Wave network traffic, and I've found that the Motion Sensor (ZW+) simply doesn't answer the BATTERY_GET call every time. I've found a ~60% success rate. So it's a problem Fibaro must fix unfortunately.

**Comment by Corvo** [comment] 2016-11-30 07:49
@WeeJeWel:
I've setup a flow that triggers upon a change in battery level and then log this into a BetterLogic variable.
Are you also implying that the Multi Sensor does not send out this event?

I understand that the `BATTERY_GET` isn't playing nice... but after all this time I've never seen a change (trigger) in battery level either. My corresponding BetterLogic variable is still set to my initial value of `0`.

**Comment by WeeJeWel** [comment] 2016-11-30 11:29
@Corvo It's simple: Homey sends a request for the battery status, but the motion sensor doesn't respond. I've seen it happen some times when waking up the device manually (triple-clicking the button), maybe that behavior is even different from a regular (wakeup interval) report.

**Comment by Corvo** [comment] 2016-11-30 11:41
@WeeJeWel From what I read a Fibaro HomeCenter2 can update it's associated Multi Sensors. Is this feature reserved to HomeCenter2 only, or is this feature coming to Homey (somewhere down the road)?

I wouldn't be suprised if the `BATTERY_GET` issue is resolved in an update... and Homey users are simply 'stuck' on their 'boxed' version.

**Comment by WeeJeWel** [comment] 2016-11-30 11:42
Updating Z-Wave devices probably won't be supported anytime soon, so if you have a HomeCenter, try updating through there!

**Comment by Corvo** [comment] 2016-11-30 11:43
@WeeJeWel Guess what I don't have...
(why would I, I've got Homey, right? ;) )

**Comment by WeeJeWel** [comment] 2016-11-30 11:44
<3

(In theory, the firmware update command class is supported, so support could be made by you or any community member)

**Comment by caseda** [comment] 2016-11-30 14:15
Just to add a little (not that unimportant) side note if you want to try and make a script for the FW update Command Class:

If you do it wrong, you might brick your sensor and need to send it back to the manufacturer to let them flash the firmware so it works again.

I'm not going to burn my fingers on this one 😁

**Comment by aelsenaar** [comment] 2017-01-05 11:04
Looks like I have the same problem with both my Fibaro motion sensors. Not only the battery is not show  but also the temperature is sometimes missing. See screenshot:
![screenshot_20170105_115118](https://cloud.githubusercontent.com/assets/16883460/21678341/a4918374-d33e-11e6-8daf-6715c8f51b25.png)

Is it a possibility to not update the values in the user interface when the sensor is not reporting values? I am very new to Homey and not familiar yet with the api otherwise I would check myself. :-)

**Comment by Corvo** [comment] 2017-01-05 11:14
@aelsenaar 
If Homey has restarted an no values were received, then the `-` is shown as a value. _(a restart can occur because of a firmware update of Homey)_
As long as Homey doesn't receive a value, this will remain a `-`...

I'm guessing that if you pick your sensor, the value of the Tamper-alarm (Sabotagealarm) will change to "Ja"... and after a while will receive the new value and from then on "Nee" will be shown.
Same goes for Lux (Helderheid), etc.

And yes, the battery-level not being reported... is still a bug (which Athom, as mentioned in above posts, can't fix).

**Comment by aelsenaar** [comment] 2017-01-05 11:29
Hi @Corvo, thanks for the update.

Crystal clear. And indeed the Homey was rebooted. :-)
Is there a possibility to persist the UI values over a reboot? The battery value was clear te me.

**Comment by Corvo** [comment] 2017-01-05 11:32
That's a good question.
@WeeJeWel and/or @RobinBol might be able to shed some light on this.

**Comment by RobinBol** [comment] 2017-01-09 12:40
We'll not be persisting the mobile card values over a reboot. The mobile card now accurately displays the value of the capability, which is unknown until reported.

**Closed by RobinBol** 2017-01-09 12:40 UTC
