### ISSUE TITLE
FGSD-002 Smoke Sensor no values

### ISSUE THREAD

**Issue by mike9011** [athombv/com.fibaro#81] opened 2016-12-07 10:20 UTC
**Homey version**
1.0.3

**Issue**
The Smoke Sensor don't send his values to Homey with the default settings.
It can take up to 3 days before the temp. value is passed through, while the temperture is changed more than the threshold.

The "Rookmelder" and "Hittealarm" never gives any value, only after a re-pair. When Homey is rebooted the values become empty again.

**Edit:** The build in range test is positive.

![fibarosmoke](https://cloud.githubusercontent.com/assets/18025163/20963773/1d95eb3e-bc6f-11e6-8c6c-27ec7183683a.PNG)

**Comment by Keverjeroen** [comment] 2016-12-09 11:08
I have 2 Fibaro Z-wave + smoke sensors. 1 Gives all values (_rookmelder = nee, hittealarm = nee, temperatuur = 21_). The other one only shows temperature. _Rook = -_ and _hitte = -_.

**Comment by RobinBol** [comment] 2016-12-09 11:58
This will likely be fixed in Homey >1.0.3. Please let me know if you still encounter problems by then.

**Comment by mike9011** [comment] 2016-12-09 12:12
I have 1.0.3, still the same issue...

**Comment by RobinBol** [comment] 2016-12-09 12:13
Yes, > means all versions above 1.0.3!

**Comment by mike9011** [comment] 2016-12-17 14:03
1.0.4. Still the same issue...
After a re-pair it works.. after a reboot everything is gone.

**Comment by RobinBol** [comment] 2016-12-17 14:45
Well, that makes sense. After a reboot the values are empty because Homey requests the node for its status, but as it is a battery device it will most likely be asleep.

Have you woken up the device manually? Or waited for the default wake up interval to pass? Have you tried forcing a smoke alarm?

**Comment by mike9011** [comment] 2016-12-20 19:05
Yep, manually woke up the sensor, made a alarm.. but still no values, only temperature.
Did a re-pair, everything was fine but after a reboot of Homey the values stay empty for 3 days now.

**Comment by caseda** [comment] 2016-12-20 20:25
what is the wakeup interval on

**Comment by RobinBol** [comment] 2016-12-21 10:44
Would you be able to run the driver for this device in debug mode from the command line/terminal and send me the output once you have forced an alarm?

Add the debug flag to enable debugging, then run from terminal/command line and it will show logging:

```
module.exports = new ZwaveDriver( path.basename(__dirname), {
	debug: true,
	capabilities: {}
})
```

**Comment by backslashgithub** [comment] 2016-12-24 15:15
fixed this problem with "verwijder een apparaat" in settings z-wave. then press 3 times on device. reboot en reinstall...

**Comment by RobinBol** [comment] 2017-01-04 15:25
@mike9011 are you still experiencing this issue? If yes could you try what I proposed in my earlier comment?

**Comment by chrisboer** [comment] 2017-01-04 15:59
Not any issues here on this device with 1.1.2 and fibaro 1.1.8 

![rookmelder_temp](https://cloud.githubusercontent.com/assets/23163409/21648675/1583ad1e-d29f-11e6-8b8f-8a4c44c0afe8.jpg)

It shows the correct temperature.

**Comment by backslashgithub** [comment] 2017-01-16 15:27
@RobinBol , how can i run the driver. what do i need to do this. want to help and start with some understanding how and what...

**Comment by RobinBol** [comment] 2017-01-16 15:31
To learn how to side load an app on your homey: https://developers.athom.com/library/getting-started/

You will need to edit the zwavedriver file in node_modules/homey-zwavedriver within the app as stated above.

**Comment by chrisboer** [comment] 2017-01-16 21:27
It will only give status reports on smoke and heat ones you hit those so, if you blow in some smoke or increase the heat you should get an alert. And a reading.

You should see the temparature anyway.

Maybe you can change your settings to this.
![rookmelder](https://cloud.githubusercontent.com/assets/23163409/21999544/f1ec47a8-dc3a-11e6-86ed-c3e0dbec022d.jpg)
![rookmelderstatus](https://cloud.githubusercontent.com/assets/23163409/21999551/fb141e8c-dc3a-11e6-99cc-1087cc016867.jpg)

**Comment by backslashgithub** [comment] 2017-01-20 10:53
1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.1.37:80...
3/4 - Running `com.aeotec`, press CTRL+C to abort...
(node:19690) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
4/4 - Debugging...

-------------------------------------------------
com.aeotec running...

waiting for 10 minutes, then i checked the device but still only seeing the temperature , smoke and heat is still " - ".
going to abort.

**Comment by caseda** [comment] 2017-01-20 13:25
Really a debug start of the app aeotec on the Fibaro github repository...
But you still need to add the debug: true tag, like stated above a few messages back

**Comment by backslashgithub** [comment] 2017-01-20 19:20
1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.1.37:80...
3/4 - Running `com.aeotec`, press CTRL+C to abort...
(node:23470) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
4/4 - Debugging...

-------------------------------------------------
com.aeotec running...
Error: missing_options_capability: measure_battery
    at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:47:11
    at Array.forEach (native)
    at ZwaveDriver (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:45:28)
    at Object.<anonymous> (/drivers/ZW100/driver.js:209:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /homey-app/manager/drivers.js:74:27
    at Array.forEach (native)
    at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)
    at /homey-app/manager/drivers.js:20:38
    at /homey-app/homey.js:1:1080
    at Array.forEach (native)
    at Object.<anonymous> (/homey-app/homey.js:1:1058)
    at emitNone (events.js:67:13)
    at Object.emit (events.js:166:7)
    at /bootstrap.js:226:9
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

--- INFO: com.aeotec has been killed ---

**Comment by caseda** [comment] 2017-01-21 08:17
What device are you trying to debug by the way @backslashgithub there are 12 drivers in the aeotec app, and you never mentioned even once
1. which device you have problems with
2. what the problem is you are having

3. kinda side tracking but please post any AEOTEC issues in the [AEOTEC repository](https://github.com/athombv/com.aeotec)
so please continue this issue over there
hoped you noticed that i was pointing towards that, but allas it did not

**Comment by backslashgithub** [comment] 2017-01-21 15:26
same problem on two device's. FGSD-002 Smoke Sensor and the Fibaro multisensor 6

**Comment by RobinBol** [comment] 2017-02-16 17:48
Will close this issue due to inactivity from the issue creator. If you are still having these issues please re-open!

**Closed by RobinBol** 2017-02-16 17:48 UTC
